FROM node:20-slim AS deps
WORKDIR /app
COPY website/nextjs/package.json website/nextjs/package-lock.json ./
RUN npm ci

FROM node:20-slim AS builder
WORKDIR /app
COPY website/nextjs/ .
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
