'use client'

import { useState } from 'react'
import { D } from '@/components/Dashboard/tokens'
import { BlockMapTab } from '@/components/Dashboard/BlockMapTab'
import { ReportTab } from '@/components/Dashboard/ReportTab'

type Tab = 'blockmap' | 'report'

const TOP = 'AXALON SYSTEMS  |  AXA-9 MISSION REPORT  |  BLOCK 04 – 15.2 MW  |  01 JUNE 2026'
const BOTTOM = 'GENERATED BY AXA-9 EDGE AI  |  JETSON ORIN NANO 8GB  |  IEC TS 62446-3 COMPLIANT'

const tabs: Array<{ id: Tab; label: string }> = [
  { id: 'blockmap', label: 'BLOCK MAP' },
  { id: 'report', label: 'REPORT & WORK ORDER' },
]

export default function DashboardPage() {
  const [active, setActive] = useState<Tab>('blockmap')

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      {/* ── Top bar ───────────────────────────────────────── */}
      <header
        style={{
          flex: '0 0 auto',
          height: 44,
          display: 'flex',
          alignItems: 'center',
          padding: '0 1.5rem',
          borderBottom: `1px solid ${D.panelBorder}`,
          fontFamily: D.mono,
          fontSize: '0.72rem',
          letterSpacing: '0.08em',
          color: D.text,
          background: 'rgba(255,255,255,0.02)',
        }}
      >
        {TOP}
      </header>

      {/* ── Tab switcher ──────────────────────────────────── */}
      <nav
        style={{
          flex: '0 0 auto',
          display: 'flex',
          justifyContent: 'center',
          gap: '2.5rem',
          borderBottom: `1px solid ${D.panelBorder}`,
        }}
      >
        {tabs.map((t) => {
          const on = active === t.id
          return (
            <button
              key={t.id}
              onClick={() => setActive(t.id)}
              style={{
                background: 'none',
                border: 'none',
                padding: '0.85rem 0.25rem',
                fontFamily: D.mono,
                fontSize: '0.72rem',
                letterSpacing: '0.16em',
                color: on ? D.teal : D.muted,
                borderBottom: `2px solid ${on ? D.teal : 'transparent'}`,
                marginBottom: -1,
                transition: 'color 0.15s',
              }}
            >
              {t.label}
            </button>
          )
        })}
      </nav>

      {/* ── Tab content ───────────────────────────────────── */}
      <main style={{ flex: '1 1 0', minHeight: 0, overflow: 'auto' }}>
        {active === 'blockmap' ? <BlockMapTab /> : <ReportTab />}
      </main>

      {/* ── Bottom bar ────────────────────────────────────── */}
      <footer
        style={{
          flex: '0 0 auto',
          height: 36,
          display: 'flex',
          alignItems: 'center',
          padding: '0 1.5rem',
          borderTop: `1px solid ${D.panelBorder}`,
          fontFamily: D.mono,
          fontSize: '0.65rem',
          letterSpacing: '0.08em',
          color: D.muted,
          background: 'rgba(255,255,255,0.02)',
        }}
      >
        {BOTTOM}
      </footer>
    </div>
  )
}
